using UnityEngine;

public class FenceCtrlNoSound : MonoBehaviour
{
    public float explosionForce = 800f;
    public float explosionRadius = 3f;
    public float upwardsModifier = 0.5f;

    public GameObject fence; // í”„ë¦¬íŒ¹
    private Rigidbody _rb;

    private Vector3 initialPosition;
    private Quaternion initialRotation;

    void Start()
    {
        _rb = GetComponent<Rigidbody>();
        _rb.isKinematic = false;
        _rb.constraints = RigidbodyConstraints.FreezeAll;
        // âœ… ì´ˆê¸° ìœ„ì¹˜ ì €ì¥
        initialPosition = transform.position;
        initialRotation = transform.rotation;
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("EnemyCar")||other.CompareTag("PlayerCar"))
        {
            Vector3 explosionPos = other.transform.position;

            // âœ… Constraints í•´ì œ í›„ í­ë°œ
            _rb.constraints = RigidbodyConstraints.None;
            _rb.AddExplosionForce(explosionForce, explosionPos, explosionRadius, upwardsModifier, ForceMode.Impulse);
            // SoundManager.Instance.Play3DSfx(SoundManager.Sfx.FenceBreak,0.5f);
            // Debug.Log("ğŸš— Fence hit by car â†’ flying!");

            // âœ… 5ì´ˆ í›„ ì¬ìƒì„±
            Invoke(nameof(Regen), 5f);
        }
    }

    void Regen()
    {
        // âœ… ì´ˆê¸° ìœ„ì¹˜ì— ìƒˆë¡œ ìƒì„±
        Instantiate(fence, initialPosition, initialRotation);
        Destroy(gameObject);
    }
}